(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var m=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},p=m(this),q="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var u;a:{var v={a:!0},w={};try{w.__proto__=v;u=w.a;break a}catch(a){}u=!1}r=u?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var x=r,y=function(a,b){a.prototype=q(b.prototype);a.prototype.constructor=a;if(x)x(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,c);f&&Object.defineProperty(a,c,f)}else a[c]=b[c];a.S=b.prototype},z=this||self,A=function(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.T=function(f,d,e){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[d].apply(f,
g)}};var D=function(a){a=1-a;return 1-a*a*a};var E=/[^\d]+$/,F=function(a,b,c,f){if(!a.hasAttribute(b))return c;a=a.getAttribute(b);isNaN(parseFloat(a))?f=c:(c=parseFloat(a),(a=(a=a.match(E))&&a[0]||null)&&(a=a.trim()),b=c,"%"==a&&(b=Number((c/100*f).toFixed(2))),f=b);return f};var aa=function(a,b,c){var f=F(a,"xenter",0,b),d=a.hasAttribute("xmiddle")?F(a,"xmiddle",0,b):void 0,e=F(a,"xexit",0,b),g=F(a,"yenter",0,c),l=a.hasAttribute("ymiddle")?F(a,"ymiddle",0,c):void 0,h=F(a,"yexit",0,c),k=G(a,"opacityenter"),n=G(a,"opacitymiddle"),B=G(a,"opacityexit"),C=a.hasAttribute("fixed"),T=a.getAttribute("assettype")||"",U=a.getAttribute("source")||"",V=a.getAttribute("easing")||"linear";b=F(a,"width",b,b);c=F(a,"height",c,c);var W=a.hasAttribute("yawenter")?parseInt(a.getAttribute("yawenter"),
10):void 0,X=a.hasAttribute("yawmiddle")?parseInt(a.getAttribute("yawmiddle"),10):void 0,Y=a.hasAttribute("yawexit")?parseInt(a.getAttribute("yawexit"),10):void 0,Z=a.getAttribute("exit-url")||void 0,t=[];t.push({opacity:k,x:f,y:g,l:W});void 0!==d&&void 0!==l&&t.push({opacity:n,x:d,y:l,l:X});t.push({opacity:B,x:e,y:h,l:Y});return{K:T,h:t,easing:V,element:a,C:Z,fixed:C,height:c,source:U,width:b}},H=function(a,b,c,f,d,e){d=void 0===d?0:d;e=void 0===e?1:e;if(f<=d)return a;if(f>=e)return b;switch(c){case "ease-in":c=
f*f*f;d*=d*d;e*=e*e;break;case "ease-in-out":c=3*f*f-2*f*f*f;d=3*d*d-2*d*d*d;e=3*e*e-2*e*e*e;break;case "ease-out":c=D(f);d=D(d);e=D(e);break;default:c=f}return 1/(e-d)*(b-a)*(c-d)+a},G=function(a,b){if(!a.hasAttribute(b))return 1;a=a.getAttribute(b);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};var I=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};function J(a){if(Error.captureStackTrace)Error.captureStackTrace(this,J);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}A(J,Error);J.prototype.name="CustomError";var K=function(a,b){a=a.split("%s");for(var c="",f=a.length-1,d=0;d<f;d++)c+=a[d]+(d<b.length?b[d]:"%s");J.call(this,c+a[f])};A(K,J);K.prototype.name="AssertionError";var ba=function(a,b,c){if(!a){var f="Assertion failed";if(b){f+=": "+b;var d=Array.prototype.slice.call(arguments,2)}throw new K(""+f,d||[]);}return a},ca=function(a,b){throw new K("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var M=function(a,b){this.A=b===L?a:""};M.prototype.N=!0;M.prototype.L=function(){return this.A.toString()};M.prototype.toString=function(){return this.A.toString()};var da=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,L={};var N=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ea=function(a){if(N(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&N(a))return a;return null};var O=function(a,b,c){c=void 0===c?null:c;var f=document.createEvent("CustomEvent");f.initCustomEvent(a,!0,!0,c);b.dispatchEvent(f);return f};var fa=[],P=function(){var a=HTMLElement.call(this)||this;a.u=[];a.H=null;a.m=null;a.j=[0,1];a.i=[];a.v=a.M.bind(a);a.B=!1;a.I=!1;a.J=a.R.bind(a);a.G=0;a.F=a.P.bind(a);a.D=a.O.bind(a);a.o=null;return a};y(P,HTMLElement);
P.prototype.connectedCallback=function(){this.ownerDocument.addEventListener("hostpagescroll",this.J);window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.F),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.D));if(!this.gwdIsLoaded()){var a=ea(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};
P.prototype.disconnectedCallback=function(){this.ownerDocument.removeEventListener("hostpagescroll",this.J);window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.F),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.D));this.removeEventListener("ready",this.v,!1)};
P.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){this.i.length=0;this.initializeParallax(!0);for(var a=this.i.length-1;0<=a;a--)this.i[a].gwdLoad();this.i=this.i.filter(function(b){return!b.gwdIsLoaded()});0==this.i.length?Q(this):this.addEventListener("ready",this.v,!1)}};P.prototype.gwdIsLoaded=function(){return this.B&&0==this.i.length};P.prototype.M=function(a){a=this.i.indexOf(a.target);0<=a&&(this.i.splice(a,1),0==this.i.length&&(Q(this),this.removeEventListener("ready",this.v,!1)))};
var Q=function(a){a.I||O("ready",a);a.I=!0;a.o&&(R(a,a.o.creativeFramePercentY,a.o.windowHeight+a.m),a.o=null)};
P.prototype.initializeParallax=function(a){var b=this;this.style.overflow="hidden";this.u.length=0;this.H=this.clientWidth;this.m=this.clientHeight;this.j=ha(this);for(var c=this.ownerDocument,f={},d=0;d<this.children.length;f={s:f.s},d++)if(!this.children[d].hasAttribute("data-gwd-csd-ghost-id")){var e=aa(this.children[d],this.H,this.m);this.u.push(e);e.element.style.position="absolute";e.element.style.left="0px";e.element.style.top="0px";e.element.style.width=e.width+"px";e.element.style.height=
e.height+"px";e.element.style.transform="translate("+e.h[0].x+"px, "+e.h[0].y+"px)";e.element.style.opacity=e.h[0].opacity+"";void 0!=e.h[0].l&&e.element.setTargetYaw(e.h[0].l);if(a){if("image"==e.K&&e.source){for(;e.element.firstChild;)e.element.removeChild(e.element.firstChild);var g=c.createElement("gwd-image");g.style.width="100%";g.style.height="100%";g.setAttribute("source",e.source);this.i.push(g);e.element.appendChild(g)}else e.element.gwdLoad&&this.i.push(e.element);e.C&&(f.s=e.C,e.element.addEventListener("click",
function(l){return function(){if(!O("layerclickexit",b,{url:l.s}).detail.handled){var h=l.s;h instanceof M||h instanceof M||(h="object"==typeof h&&h.N?h.L():String(h),ba(da.test(h),"%s does not match the safe URL pattern",h)||(h="about:invalid#zClosurez"),h=new M(h,L));var k=h;h=z.open;if(k instanceof M&&k.constructor===M)k=k.A;else{var n=typeof k;ca("expected object of type SafeUrl, got '"+k+"' of type "+("object"!=n?n:k?Array.isArray(k)?"array":n:"null"));k="type_error:SafeUrl"}h.call(z,k,"")}}}(f)))}}this.B=
!0};P.prototype.R=function(a){a=a.detail;this.G=a.creativeFramePercentY;this.gwdIsLoaded()?R(this,a.creativeFramePercentY,a.windowHeight+this.m):this.o=a};
var R=function(a,b,c){for(var f=0;f<a.u.length;f++){var d=a.u[f],e=void 0,g=void 0;e=d.h.length-1;var l=a.j[0],h=a.j[a.j.length-1],k=d.h[0],n=d.h[d.h.length-1];if(d.h.length===a.j.length)for(g=0;g<e;g++)if(a.j[g]<=b&&b<=a.j[g+1]){l=a.j[g];h=a.j[g+1];k=d.h[g];n=d.h[g+1];break}d.fixed?(e=d.h[0].x,g=d.h[0].y+b*c):(e=H(k.x,n.x,d.easing,b,l,h),g=H(k.y,n.y,d.easing,b,l,h));var B=H(k.opacity,n.opacity,d.easing,b,l,h);d.element.style.transform="translate("+e+"px, "+g+"px)";d.element.style.opacity=B+"";d.h.some(function(C){return void 0===
C.l})||d.element.setTargetYaw(Math.round(H(k.l,n.l,d.easing,b,l,h)))}O("parallaxscrolled",a,{yscroll:b})},ha=function(a){var b=I(a,"start",0),c=I(a,"end",1);if(0>b||1<b||0>c||1<c||b>=c)b=0,c=1;a=I(a,"middle",-1);return a>=b&&a<=c?[b,a,c]:[b,c]};P.prototype.P=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);R(a,1,window.innerHeight+a.m)},0)};P.prototype.O=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);R(a,a.G,window.innerHeight+a.m)},0)};
p.Object.defineProperties(P,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return fa}}});var S=function(){return P.call(this)||this};y(S,P);customElements.define("gwd-parallax",S);}).call(this);
