(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={a:!0},p={};try{p.__proto__=n;m=p.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var q=l,r=function(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.R=function(d,e,h){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}};var t=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},u=function(a){a=parseFloat(a.getAttribute("time-limit"));isFinite(a)||(a=-1);return 0<a?a:-1};var v=/[^\d]+$/,w=function(a,b,c){if(!a.hasAttribute(b))return 0;b=a.getAttribute(b);if(isNaN(parseFloat(b)))c=0;else{a=parseFloat(b);(b=(b=b.match(v))&&b[0]||null)&&(b=b.trim());var d=a;"%"==b&&(d=Number((a/100*c).toFixed(2)));c=d}return c};var x=function(a,b){var c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)};var y=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},z=function(a){if(y(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&y(a))return a;return null};function A(a){if(Error.captureStackTrace)Error.captureStackTrace(this,A);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(A,Error);A.prototype.name="CustomError";var B=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");A.call(this,c+a[d])};r(B,A);B.prototype.name="AssertionError";var C=function(a,b,c){if("number"!==typeof a){var d=typeof a,e=["object"!=d?d:a?Array.isArray(a)?"array":d:"null",a];d="Assertion failed";b?(d+=": "+b,e=Array.prototype.slice.call(arguments,2)):d+=": Expected number but got %s: %s.";throw new B(""+d,e||[]);}return a};var D=function(){var a=HTMLElement.call(this)||this;a.canvas=null;a.s=!1;a.g=[];a.B=a.M.bind(a);a.L=a.N.bind(a);a.m=a.O.bind(a);a.u=[];a.C=a.G.bind(a);a.h=null;a.i=2;a.v=null;a.o=-1;a.A=null;a.I=!1;return a},E=HTMLElement;D.prototype=f(E.prototype);D.prototype.constructor=D;if(q)q(D,E);else for(var G in E)if("prototype"!=G)if(Object.defineProperties){var H=Object.getOwnPropertyDescriptor(E,G);H&&Object.defineProperty(D,G,H)}else D[G]=E[G];D.P=E.prototype;
D.prototype.connectedCallback=function(){var a=this;this.width=this.clientWidth;this.height=this.clientHeight;this.l=window.devicePixelRatio;this.canvas||(this.canvas=this.ownerDocument.createElement("canvas"),this.appendChild(this.canvas));this.canvas.style.width=this.width+"px";this.canvas.style.height=this.height+"px";this.canvas.width=this.width*this.l;this.canvas.height=this.height*this.l;this.j=this.canvas.getContext("2d");this.K=this.hasAttribute("autoplay");null===this.A?this.o=1E3*u(this):
this.I&&this.play();setTimeout(function(){if(!a.gwdIsLoaded()){var b=z(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},0)};D.prototype.disconnectedCallback=function(){this.gwdIsLoaded()?(this.I=0==this.i,this.pause(!1)):I(this)};
D.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){I(this);for(var a=0,b=0;b<this.children.length;b++){var c=this.children[b];if(J(c))c.gwdIsLoaded()||K(this,c),this.addEventListener("request-reload",this.L,!1);else if("image"==c.getAttribute("assettype")){var d=c.getAttribute("source"),e=w(c,"left",this.width),h=w(c,"top",this.height),k=w(c,"width",this.width),g=w(c,"height",this.height),F=t(c,"opacity",100);d={canvas:null,src:d,F:e*this.l,H:h*this.l,J:k*this.l,D:g*this.l,opacity:Math.min((0<=
F?F:100)/100,1)};e=this.ownerDocument.createElement("img");this.g.push(e);e.addEventListener("load",this.m,!1);e.addEventListener("error",this.m,!1);this.u[a]=d;c.setAttribute("image-index",a);e.setAttribute("image-index",a++);e.width=d.J;e.height=d.D;e.src=d.src}}this.s=!0;L(this)}};D.prototype.gwdIsLoaded=function(){return this.s&&0==this.g.length};
var K=function(a,b){-1==a.g.indexOf(b)&&(a.g.push(b),b.addEventListener("ready",a.B,!1));b.gwdLoad()},I=function(a){for(;a.g.length;){var b=a.g.pop();b.removeEventListener("ready",a.B,!1);b.removeEventListener("load",a.m,!1);b.removeEventListener("error",a.m,!1)}a.s=!1;a.u.length=0},L=function(a){a.s&&0==a.g.length&&(x("ready",a),a.K?a.play(!0):null!=a.v&&a.play(a.v),a.v=null)};
D.prototype.M=function(a){a=a.target;var b=this.g.indexOf(a);0<=b&&(this.g.splice(b,1),a.removeEventListener("ready",this.B,!1),L(this))};D.prototype.N=function(a){K(this,a.target)};
D.prototype.O=function(a){var b=this,c=a.target;c.removeEventListener("load",this.m,!1);c.removeEventListener("error",this.m,!1);var d=this.g.indexOf(c);if(0<=d){var e=parseInt(c.getAttribute("image-index"),10);if("load"==a.type){var h=this.ownerDocument.createElement("canvas");h.width=c.width;h.height=c.height;var k=this.u[e],g=h.getContext("2d");g.globalAlpha=k.opacity;setTimeout(function(){d=b.g.indexOf(c);b.g.splice(d,1);g.drawImage(c,0,0,c.width,c.height);k.canvas=h;L(b)},50)}else this.g.splice(d,
1),L(this)}};var J=function(a){return"gwd-particles"==a.tagName.toLowerCase()};D.prototype.play=function(a){a=void 0===a?!0:a;if(!this.gwdIsLoaded())this.v=0!=a;else if(0!=this.i){null==this.A&&(this.A=Date.now());if(2==this.i)for(var b=0;b<this.children.length;b++){var c=this.children[b].hasAttribute("autoplay");J(this.children[b])&&c&&this.children[b].play()}0==a?this.G(!1):this.h=requestAnimationFrame(this.C);this.i=0}};
D.prototype.pause=function(a){a=void 0===a?!0:a;this.h&&(cancelAnimationFrame(this.h),this.h=null,a&&(this.o=-1),this.i=1)};D.prototype.stop=function(){if(2!=this.i){for(var a=0;a<this.children.length;a++)J(this.children[a])&&this.children[a].stop();this.h&&(cancelAnimationFrame(this.h),this.h=null,this.o=-1);this.i=2;this.j.clearRect(0,0,this.canvas.width,this.canvas.height)}};
D.prototype.G=function(a){if(0!=a&&0<this.o&&Date.now()-C(this.A)>this.o)this.pause(),x("timelimitreached",this);else{this.j.clearRect(0,0,this.canvas.width,this.canvas.height);for(var b=0;b<this.children.length;b++){var c=this.children[b];c.hasAttribute("hidden")||(J(c)&&c.gwdIsLoaded()?c.updateAndDraw():"image"==c.getAttribute("assettype")&&(c=t(c,"image-index",-1),-1!=c&&(c=this.u[c],c.canvas?this.j.drawImage(c.canvas,c.F,c.H):this.hasAttribute("data-gwd-node")&&(this.j.strokeStyle="#c0c0c0",this.j.lineWidth=
1,this.j.strokeRect(c.F,c.H,c.J,c.D)))))}0!=a&&(this.h=requestAnimationFrame(this.C))}};customElements.define("gwd-particleeffects",D);}).call(this);
