(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");},ca=ba(this),k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var q;a:{var da={a:!0},u={};try{u.__proto__=da;q=u.a;break a}catch(a){}q=!1}k=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var v=k;var ea={A:0,B:0,C:0,D:0,F:"#fff",G:"#fff",H:0,u:0,l:0,I:"0px",J:"0px",K:"0px",L:"0px",loop:!1,M:0,N:1,O:1,P:0,S:!1,shape:"square",U:1,V:1,W:0,X:0,o:0,s:0,ea:"",T:!1,v:1,Y:0,j:1,Z:1},fa={A:0,B:0,C:280,D:260,F:"#fff",G:"#fff",H:0,u:.005,l:2,I:"100%",J:"0%",K:"10%",L:"0%",loop:!0,M:0,N:1,O:.1,P:0,S:!0,shape:"circle",U:12,V:8,W:0,X:0,o:2,s:1,ea:"",T:!1,v:1,Y:0,j:1,Z:1},ha={A:0,B:.6,C:271,D:269,F:"#fff",G:"#fff",H:0,u:.01,l:2,I:"100%",J:"0%",K:"10%",L:"0%",loop:!0,M:0,N:1,O:.5,P:0,S:!0,shape:"line",U:25,
V:10,W:0,X:100,o:10,s:8,ea:"",T:!1,v:1,Y:0,j:1,Z:1},ia={A:0,B:.6,C:100,D:80,F:"#ffdc00",G:"#dc000a",H:1.2,u:0,l:1,I:"20px",J:"10px",K:"40px",L:"35px",loop:!0,M:10,N:.3,O:.1,P:-.3,S:!1,shape:"teardrop",U:20,V:20,W:-30,X:100,o:1,s:.5,ea:"",T:!0,v:20,Y:.18,j:1,Z:30},ja={A:0,B:.6,C:100,D:80,F:"#ffdc00",G:"#dc000a",H:1,u:0,l:2,I:"50px",J:"20px",K:"100px",L:"95px",loop:!0,M:15,N:.3,O:.1,P:-.3,S:!1,shape:"teardrop",U:40,V:40,W:-30,X:100,o:2,s:1,ea:"",T:!0,v:20,Y:.18,j:1,Z:30},ka={A:0,B:.6,C:100,D:80,F:"#ffdc00",
G:"#dc000a",H:.8,u:0,l:4,I:"80px",J:"30px",K:"180px",L:"175px",loop:!0,M:15,N:.3,O:.1,P:-.3,S:!1,shape:"teardrop",U:100,V:100,W:-54,X:100,o:3,s:2,ea:"",T:!0,v:20,Y:.18,j:1,Z:25},la={A:0,B:0,C:90,D:90,F:"#dcdcdc",G:"#dcdcdc",H:0,u:0,l:25,I:"22px",J:"10px",K:"120px",L:"100px",loop:!0,M:8,N:.03,O:.03,P:-.018,S:!0,shape:"teardrop",U:15,V:15,W:-.06,X:100,o:1,s:.8,ea:"",T:!0,v:60,Y:.6,j:.5,Z:40},ma={A:0,B:.06,C:100,D:80,F:"#dcdcdc",G:"#dcdcdc",H:0,u:0,l:2,I:"35px",J:"10px",K:"150px",L:"148px",loop:!0,M:300,
N:.1,O:.1,P:-.03,S:!0,shape:"circle",U:20,V:10,W:-1.2,X:100,o:.8,s:.8,ea:"",T:!0,v:10,Y:0,j:.5,Z:1};var w=function(a,b,d){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=d);return a},A=function(a,b,d){a=w(a,b,d);return 0<a?a:d},B=function(a,b,d){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=d);return a},C=function(a,b,d){return a.hasAttribute(b)?a.getAttribute(b):d},D=function(a,b,d){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return d}};var na=/[^\d]+$/,G=function(a,b,d,c){if(!a.hasAttribute(b))return d;a=a.getAttribute(b);return isNaN(parseFloat(a))?d:E(a,c)},E=function(a,b){var d=parseFloat(a);(a=(a=a.match(na))&&a[0]||null)&&(a=a.trim());var c=d;"%"==a&&(c=Number((d/100*b).toFixed(2)));return c};var oa=/^#(?:[0-9a-f]{3}){1,2}$/i,pa=/#(.)(.)(.)/,H=[60,6E3],I=function(a){if(!oa.test(a))return null;4==a.length&&(a=a.replace(pa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},J=function(a,b,d,c,e){b=B(a,b,c);a=B(a,d,e);b>a&&(d=b,b=a,a=d);return[b,a]},qa=function(a){switch(a){case "snow":return fa;case "rain":return ha;case "fire-small":return ia;case "fire-medium":return ja;case "fire-large":return ka;case "steam":return la;case "smoke":return ma;default:return ea}},
K=function(a,b,d,c,e,f){b=G(a,b,c,f);a=G(a,d,e,f);b>a&&(d=b,b=a,a=d);return[b,a]};var L=function(a,b,d){return a+d*(b-a)},M=function(a){return a*a*a*(a*(6*a-15)+10)},P=function(a,b,d,c){switch(a%16){case 0:return b+d;case 1:return-b+d;case 2:return b-d;case 3:return-b-d;case 4:return b+c;case 5:return-b+c;case 6:return b-c;case 7:return-b-c;case 8:return d+c;case 9:return-d+c;case 10:return d-c;case 11:return-d-c;case 12:return b+d;case 13:return-d+c;case 14:return-b+d;case 15:return-d-c;default:return 0}},ra=function(){for(var a=Array(256),b=0;b<a.length;++b)a[b]=b;for(b=a.length-
1;0<b;--b){var d=Math.floor(Math.random()*a.length),c=a[b];a[b]=a[d];a[d]=c}this.Za=a.concat(a)},Q=function(a,b,d,c){var e=b&255,f=d&255,g=c&255;b-=Math.floor(b);d-=Math.floor(d);c-=Math.floor(c);var l=M(b),h=M(d);a=a.Za;return L(L(L(P(a[a[a[e]+f]+g],b,d,c),P(a[a[a[e+1]+f]+g],b-1,d,c),l),L(P(a[a[a[e]+f+1]+g],b,d-1,c),P(a[a[a[e+1]+f+1]+g],b-1,d-1,c),l),h),L(L(P(a[a[a[e]+f]+g+1],b,d,c-1),P(a[a[a[e+1]+f]+g+1],b-1,d,c-1),l),L(P(a[a[a[e]+f+1]+g+1],b,d-1,c-1),P(a[a[a[e+1]+f+1]+g+1],b-1,d-1,c-1),l),h),M(c))};var R=function(a){this.Ma=a;this.Ja=[];this.length=this.pa=0};R.prototype.get=function(a){return this.Ja[(a+this.pa)%this.length]};R.prototype.push=function(a){this.length<this.Ma&&this.length++;this.Ja[this.pa]=a;this.pa=(this.pa+1)%this.Ma};var sa=2*Math.PI,S=function(a,b){return a+Math.random()*(b-a)},U=function(a,b){this.m=[];this.h=b;this.i=a.getContext("2d");this.Ba=window.devicePixelRatio;this.Ga=1;this.Ka=[];this.La=[];if("image"!=this.h.ta.shape)a=null;else if((a=this.h.ta.Ya)&&0!=a.length){b=[];this.Ga=this.h.sa.max*this.Ba;for(var d=0;d<a.length;d++){var c=a[d],e=document.createElement("canvas"),f=e.getContext("2d"),g=this.Ga/Math.max(c.naturalWidth,c.naturalHeight),l=c.naturalWidth*g;g*=c.naturalHeight;e.width=Math.ceil(l);
e.height=Math.ceil(g);f.drawImage(c,0,0,l,g);b.push(e);this.Ka.push(-l/2);this.La.push(-g/2)}a=b}else this.h.ta.shape="square",a=null;this.Ca=a;this.qa=0;this.Wa=0==this.h.l?this.h.Ea:1/this.h.l;a=this.h.ga;this.Aa=a.la?0:(a.oa-a.xa)*a.Fa;this.za=a.la?0:(a.na-a.wa)*a.Fa;this.ya=a.la?0:(a.ma-a.va)*a.Fa;this.Ha=(a=this.h.Oa)?new ra:null;this.Ia=a?a.frequency:1;this.cb=a?a.ab:1;this.Pa=a&&a.bb-1||0;for(a=0;a<this.h.Na;a++)T(this)};U.prototype.reset=function(){for(var a=this.qa=this.m.length=0;a<this.h.Na;a++)T(this)};
var V=function(a){var b=S(a.h.ra.Ra,a.h.ra.Qa),d=S(a.h.ra.Ta,a.h.ra.Sa),c=S(a.h.sa.min,a.h.sa.max),e=S(a.h.Da.min,a.h.Da.max),f=a.h.ga,g=f.xa,l=f.wa,h=f.va;f.la&&(h=Math.random(),g=(1-h)*f.xa+h*f.oa,l=(1-h)*f.wa+h*f.na,h=(1-h)*f.va+h*f.ma);var n=S(a.h.ua.s,a.h.ua.o);f=S(a.h.ua.Va,a.h.ua.Ua);var y=n*Math.cos(f);n*=Math.sin(f);var x=-1;a.Ca&&(x=Math.floor(S(0,a.Ca.length)));return{g:{positionX:b,positionY:d,size:c,ba:g,aa:l,$:h,opacity:e,ia:!0,angle:f,ja:x},velocityX:y,velocityY:n,j:a.cb,fa:a.Pa?new R(a.Pa):
null}},T=function(a){for(var b=Date.now()/a.Ia,d=0;d<a.m.length;d++){var c=a.m[d],e=a;c.fa&&c.fa.push({positionX:c.g.positionX,positionY:c.g.positionY,size:c.g.size,ba:c.g.ba,aa:c.g.aa,$:c.g.$,opacity:c.g.opacity,angle:c.g.angle,ja:c.g.ja,ia:c.g.ia});if(c.g.ia){c.g.positionX+=c.velocityX;c.g.positionY+=c.velocityY;if(e.Ha&&0<c.j){var f=c.g.positionX/e.Ia,g=c.g.positionY/e.Ia;c.g.positionX+=c.j*Q(e.Ha,f,g,b);c.g.positionY+=c.j*Q(e.Ha,b,f,g);c.j+=e.h.Oa.rate}c.g.size+=e.h.sa.rate;c.g.opacity=Math.min(1,
c.g.opacity+e.h.Da.rate);c.velocityX+=e.h.acceleration.x;c.velocityY+=e.h.acceleration.y;c.g.angle=Math.atan2(c.velocityY,c.velocityX);f=e.h.ga;f.la||((!e.Aa||1<(f.oa-c.g.ba)/e.Aa)&&(!e.za||1<(f.na-c.g.aa)/e.za)&&(!e.ya||1<(f.ma-c.g.$)/e.ya)?(c.g.ba+=e.Aa,c.g.aa+=e.za,c.g.$+=e.ya):(c.g.ba=e.h.ga.oa,c.g.aa=e.h.ga.na,c.g.$=e.h.ga.ma))}if(0>c.g.positionX+c.g.size||c.g.positionX-c.g.size>a.h.width||0>c.g.positionY+c.g.size||c.g.positionY-c.g.size>a.h.height||0>c.g.opacity||0>c.g.size)a.h.$a?(c=c.fa,a.m[d]=
V(a),a.m[d].fa=c):c.g.ia=!1}if(a.m.length<a.h.Ea)for(a.qa=Math.min(a.qa+a.Wa,a.h.Ea),b=Math.floor(a.qa)-a.m.length,d=0;d<b;d++)a.m.push(V(a))},ta=function(a,b){if(b.ia){a.i.fillStyle="rgba("+Math.round(b.ba)+", "+Math.round(b.aa)+", "+Math.round(b.$)+", "+b.opacity+")";a.i.save();a.i.translate(b.positionX,b.positionY);var d=b.size/a.Ga;a.i.scale(d,d);switch(a.h.ta.shape){case "circle":a.i.beginPath();a.i.arc(0,0,.5,0,sa);a.i.fill();break;case "line":a.i.beginPath();a.i.rotate(b.angle);a.i.fillRect(-.5,
-.01,1,.02);break;case "teardrop":a.i.beginPath();a.i.moveTo(.08,-.5);a.i.bezierCurveTo(.13,-.21,.16,.04,.3,.07);a.i.bezierCurveTo(.44,.36,.13,.5,-.06,.5);a.i.bezierCurveTo(-.49,.14,-.41,0,.08,-.5);a.i.fill();break;case "image":a.i.globalAlpha=b.opacity;a.i.drawImage(a.Ca[b.ja],a.Ka[b.ja],a.La[b.ja]);break;default:a.i.beginPath(),a.i.fillRect(-.5,-.5,1,1)}a.i.restore()}};var ua=function(a,b){var d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c)};var va=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},wa=function(a){if(va(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&va(a))return a;return null},xa=function(a){return(a=C(a,"sprite-image-src",""))?a.split(",").map(function(b){return b.trim()}):[]};var ya={eb:"acceleration-x",fb:"acceleration-y",gb:"angle-max",hb:"angle-min",ib:"autoplay",jb:"color1",kb:"color2",lb:"color-rate",mb:"custom-preset",nb:"emit-interval",ob:"emit-x-max",pb:"emit-x-min",qb:"emit-y-max",rb:"emit-y-min",sb:"loop",tb:"number",ub:"opacity-max",vb:"opacity-min",wb:"opacity-rate",xb:"preset-type",yb:"random-colors",zb:"shape",Ab:"size-max",Bb:"size-min",Cb:"size-rate",Db:"skip-forward",Eb:"speed-max",Fb:"speed-min",Gb:"sprite-image-src",Hb:"turbulence-frequency",Ib:"turbulence-rate",
Jb:"turbulence-strength",Kb:"turbulence-trail"},za=[],Aa=0,Ba;for(Ba in ya)za[Aa++]=ya[Ba];var W=function(){var a=HTMLElement.call(this)||this;a.R=null;a.da=0;a.ca=[];a.ha=a.Xa.bind(a);a.ka=2;return a},X=HTMLElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;if(v)v(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Ca=Object.getOwnPropertyDescriptor(X,Y);Ca&&Object.defineProperty(W,Y,Ca)}else W[Y]=X[Y];W.prototype.attributeChangedCallback=function(){this.reset()};
W.prototype.connectedCallback=function(){if(!this.gwdIsLoaded()){var a=wa(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};W.prototype.disconnectedCallback=function(){Z(this);this.R=null};W.prototype.gwdLoad=function(){if(!this.R){Z(this);var a=xa(this);if(this.da=a.length)for(var b=0;b<this.da;b++){var d=this.ownerDocument.createElement("img");d.addEventListener("load",this.ha,!1);d.addEventListener("error",this.ha,!1);d.src=a[b];this.ca.push(d)}0===this.da&&Da(this)}};
W.prototype.gwdIsLoaded=function(){return!!this.R};
var Z=function(a){for(;a.ca.length;){var b=a.ca.pop();b.removeEventListener("load",a.ha,!1);b.removeEventListener("error",a.ha,!1)}a.da=0},Da=function(a){var b=a.getAttribute("preset-type"),d=a.ca.length?a.ca:null;if(a.parentElement){var c=a.parentElement.getElementsByTagName("canvas")[0];if(c){var e=a.parentElement.clientWidth,f=a.parentElement.clientHeight;b=qa(b);var g=E(b.J,e),l=E(b.I,e),h=E(b.L,f),n=E(b.K,f);g=K(a,"emit-x-min","emit-x-max",g,l,e);h=K(a,"emit-y-min","emit-y-max",h,n,f);h={Ra:g[0],
Qa:g[1],Ta:h[0],Sa:h[1]};n=b.M;b.u&&(n=Math.ceil(b.u*(h.Qa-h.Ra)*(h.Sa-h.Ta)));n=Math.min(A(a,"number",n),1E3);g=A(a,"emit-interval",b.l);l=b.X;var y=w(a,"skip-forward",l);l=Math.round((0<=y?y:l)*Math.min(Math.max(n*g,H[0]),H[1])/100);y=D(a,"loop",b.loop);var x=J(a,"size-min","size-max",b.V,b.U),z=B(a,"size-rate",b.W)/60;x={min:x[0],max:x[1],rate:z};z=J(a,"opacity-min","opacity-max",b.O,b.N);var t=B(a,"opacity-rate",b.P)/60;z={min:z[0],max:z[1],rate:t};t=C(a,"color1",b.F);var r=C(a,"color2",b.G);
t=I(t);r=I(r);var m=D(a,"random-colors",b.S),p=B(a,"color-rate",b.H)/60;t={la:m,xa:t[0],wa:t[1],va:t[2],oa:r[0],na:r[1],ma:r[2],Fa:p};r=J(a,"speed-min","speed-max",b.s,b.o);m=J(a,"angle-min","angle-max",b.D,b.C);m[0]=-m[0];m[1]=-m[1];r={s:r[0],o:r[1],Va:m[1]/180*Math.PI,Ua:m[0]/180*Math.PI};m=B(a,"acceleration-x",b.A)/60;p=B(a,"acceleration-y",b.B)/60;m={x:m,y:p};p=C(a,"shape",b.shape);d={shape:p,Ya:"image"==p?d:null};p=a.hasAttribute("turbulence-frequency");var F=a.hasAttribute("turbulence-strength"),
N=a.hasAttribute("turbulence-rate"),O=a.hasAttribute("turbulence-trail");b.T||p||F||N||O?(p=B(a,"turbulence-frequency",b.v),F=B(a,"turbulence-strength",b.j),N=B(a,"turbulence-rate",b.Y)/60,O=Math.min(A(a,"turbulence-trail",b.Z),100),b={frequency:0<p?p:b.v,ab:0<F?F:b.j,rate:N,bb:O}):b=null;a.R=new U(c,{width:e,height:f,Ea:n,l:g,Na:l,ra:h,sa:x,Da:z,ga:t,ua:r,acceleration:m,$a:y,ta:d,Oa:b});ua("ready",a)}}};
W.prototype.Xa=function(a){var b=a.target;b.removeEventListener("load",this.ha,!1);b.removeEventListener("error",this.ha,!1);b=this.ca.indexOf(b);0<=b&&("error"===a.type&&this.ca.splice(b,1),this.da--);0===this.da&&Da(this)};W.prototype.updateAndDraw=function(){0===this.ka&&T(this.R);if(2!=this.ka){var a=this.R;a.i.save();a.i.scale(a.Ba,a.Ba);for(var b=0;b<a.m.length;b++){var d=a.m[b];if(d.fa)for(var c=0;c<d.fa.length;c++)ta(a,d.fa.get(c));ta(a,d.g)}a.i.restore()}};
W.prototype.play=function(){this.ka=0};W.prototype.pause=function(){this.ka=1};W.prototype.stop=function(){this.ka=2;this.R.reset()};W.prototype.reset=function(){Z(this);this.R=null;ua("request-reload",this)};ca.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return za}}});customElements.define("gwd-particles",W);}).call(this);
