(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g="function"==typeof Object.create?Object.create:function(a){var c=function(){};c.prototype=a;return new c},y=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");},z=y(this),B;
if("function"==typeof Object.setPrototypeOf)B=Object.setPrototypeOf;else{var E;a:{var F={a:!0},G={};try{G.__proto__=F;E=G.a;break a}catch(a){}E=!1}B=E?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}var I=B;var J=function(a,c,b){a=parseFloat(a.getAttribute(c));isFinite(a)||(a=b);return a},K=function(a,c,b){return a.hasAttribute(c)?a.getAttribute(c):b};var L=function(a,c){var b=void 0===b?null:b;var h=document.createEvent("CustomEvent");h.initCustomEvent(a,!0,!0,b);c.dispatchEvent(h)};var M={h:"colorprimary",i:"colorsecondary",j:"gradienttype",l:"iconsize",m:"isemptycolored",o:"isemptyshown",s:"ratingmax",u:"ratingmin",v:"ratingvalue"},N=[],O=0,P;for(P in M)N[O++]=M[P];var Q=function(){var a=HTMLElement.call(this)||this;a.g=!1;return a},R=HTMLElement;Q.prototype=g(R.prototype);Q.prototype.constructor=Q;if(I)I(Q,R);else for(var S in R)if("prototype"!=S)if(Object.defineProperties){var T=Object.getOwnPropertyDescriptor(R,S);T&&Object.defineProperty(Q,S,T)}else Q[S]=R[S];
Q.prototype.connectedCallback=function(){U(this);this.g=!0};Q.prototype.attributeChangedCallback=function(){this.g&&U(this)};
var U=function(a){a.textContent="";var c=J(a,"ratingmax",5);var b=J(a,"ratingmin",3);var h=J(a,"ratingvalue",5);c=Math.round(c);b=Math.round(b);var u=Math.floor(h),C=h-u;h=Math.min(.29>C?u:.71<C?u+1:u+.5,c);u=K(a,"colorprimary","#ffcd00");C=K(a,"colorsecondary","#e16f00");var V=K(a,"gradienttype","none");var A=J(a,"iconsize",15);A=Math.min(Math.max(A,5),50);var W=a.hasAttribute("isemptycolored");var X=a.hasAttribute("isemptyshown");if(h<b)L("validationerror",a);else{b=a.ownerDocument;for(var n=a.getAttribute("id"),
p,D=0;D<c;D++){var v=p=D+1<=h?"full":D+.5==h?"half":"none";p=b.createElement("div");p.classList.add("icon-container");var f=A;p.style.width=f+"px";p.style.height=f+"px";f=b.createElementNS("http://www.w3.org/2000/svg","svg");f.setAttribute("class","svg-star");f.setAttribute("width",A);f.setAttribute("height",A);f.setAttribute("x","0");f.setAttribute("y","0");f.setAttribute("viewBox","0 0 12 12");f.setAttribute("xmlns","http://www.w3.org/2000/svg");f.setAttribute("version","1.1");var H=f,q=v,r="none"!=
q,k=X;v=W;var w=u,t=C,m=V;if(r||k){var d=b.createElementNS("http://www.w3.org/2000/svg","defs");H.appendChild(d);var l=b.createElementNS("http://www.w3.org/2000/svg","path");l.setAttribute("d","M6,8.8l3.7,2.7L8.3,7.1L12,4.5H7.4L6,0L4.6,4.5H0l3.7,2.6l-1.4,4.4L6,8.8z");l.setAttribute("id","star-path");l.setAttribute("transform","translate(0, 0) scale(1, 1)");H.appendChild(l);var e="",x=null;r?"none"==m?e=w:"radial"==m?(e="url('#radialGradient-"+n+"')",x="radialGradient"):"linear"==m&&(e="url('#linearGradient-"+
n+"')",x="linearGradient"):v?e=w:(l.setAttribute("stroke",w),l.setAttribute("stroke-width","0.3"),e="#ffffff");l.setAttribute("fill",e);x&&(m=b.createElementNS("http://www.w3.org/2000/svg",x),m.setAttribute("id",x+"-"+n),e=b.createElementNS("http://www.w3.org/2000/svg","stop"),e.setAttribute("offset","linearGradient"==x?"10%":"0%"),e.setAttribute("stop-color",w),m.appendChild(e),e=b.createElementNS("http://www.w3.org/2000/svg","stop"),e.setAttribute("offset","100%"),e.setAttribute("stop-color",t),
m.appendChild(e),d.appendChild(m));l.setAttribute("opacity",!r&&k?v?"0.4":"0.8":"1");"half"==q&&(r=b.createElementNS("http://www.w3.org/2000/svg","clipPath"),r.setAttribute("id","clip-path-left-half-"+n),t=b.createElementNS("http://www.w3.org/2000/svg","rect"),t.setAttribute("x","0"),t.setAttribute("y","0"),t.setAttribute("width","6"),t.setAttribute("height","12"),r.appendChild(t),d.appendChild(r),l.setAttribute("clip-path",'url("#clip-path-left-half-'+n+'")'));"half"==q&&k&&(q=b.createElementNS("http://www.w3.org/2000/svg",
"clipPath"),q.setAttribute("id","clip-path-right-half-"+n),k=b.createElementNS("http://www.w3.org/2000/svg","rect"),k.setAttribute("x","6"),k.setAttribute("y","0"),k.setAttribute("width","6"),k.setAttribute("height","12"),q.appendChild(k),d.appendChild(q),d=b.createElementNS("http://www.w3.org/2000/svg","path"),d.setAttribute("id","star-path-right-half"),d.setAttribute("d","M6,8.8l3.7,2.7L8.3,7.1L12,4.5H7.4L6,0L4.6,4.5H0l3.7,2.6l-1.4,4.4L6,8.8z"),d.setAttribute("clip-path",'url("#clip-path-right-half-'+
n+'")'),d.setAttribute("opacity",v?.4:.8),d.setAttribute("transform","translate(0, 0) scale(1, 1)"),H.appendChild(d),v?d.setAttribute("fill",w):(d.setAttribute("fill","#ffffff"),d.setAttribute("stroke",w),d.setAttribute("stroke-width","0.3")))}p.appendChild(f);a.appendChild(p)}L("complete",a)}};z.Object.defineProperties(Q,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return N}}});customElements.define("gwd-starratings",Q);}).call(this);
