(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f,h=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ba=aa(this),k=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:h(a)}},
ca="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},n;if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var da={a:!0},q={};try{q.__proto__=da;p=q.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var r=n,t=this||self,u=function(a,b){a=a.split(".");var c=t;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var ea=function(a){a=v(a,"autoplay-duration");return 0<a?a:29},v=function(a,b){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=29);return a};var x=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};Object.freeze&&Object.freeze([]);var y=function(a,b){var c=t.performance;a={label:a,type:9,value:c&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):Date.now()};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var z={},A=!1,B=!1;z.I=function(a){A||(A=!0,y("11",a))};z.J=function(a){B||(B=!0,y("12",a))};z.D=function(a,b,c){var d=b;d=void 0===d?t:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===c?0:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};z.reset=function(a){B=A=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};u("gwd.rumUtil",z);u("gwd.rumUtil.logContentLoading",z.I);
u("gwd.rumUtil.logContentRendered",z.J);u("gwd.rumUtil.logTimingEvent",z.D);u("gwd.rumUtil.reset",z.reset);var C=function(a){(0,z.D)("gwd3dmodelviewer_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);window.Enabler&&(a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame"))},E=function(a){window.Enabler&&(a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement"),D())},F=0,G=0;function D(){var a=Math.floor(performance.now()/100);0==F&&(F=a);for(a-=F;G<=a;G++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var H={Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}};var I=function(a,b){return window.setTimeout(a,b)};var J=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)};var K=x({K:"animation-name",S:"auto-rotate",P:"autoplay",R:"autoplay-duration",T:"camera-orbit",U:"camera-target",V:"environment-image",W:"exposure",$:"field-of-view",ea:"max-camera-orbit",fa:"max-field-of-view",ga:"min-camera-orbit",ha:"min-field-of-view",ia:"poster",ja:"reveal",ka:"shadow-intensity",la:"shadow-softness",ma:"skybox-image",na:"src"}).concat(x({L:"ar",M:"ar-modes",N:"ar-placement",O:"ar-scale",da:"ios-src"})),fa=K.concat(x({aa:"gesture-cue-duration",ba:"gesture-cue-icon",ca:"gesture-cue-text"})),
L=180/Math.PI,M=function(){var a=HTMLElement.call(this)||this;a.i=null;a.u=!1;a.B=!1;a.v=null;a.s=null;a.l="hotspot-"+(2147483648*Math.random()|0);a.j=!1;a.A=a.G.bind(a);return a},N=HTMLElement;M.prototype=ca(N.prototype);M.prototype.constructor=M;if(r)r(M,N);else for(var O in N)if("prototype"!=O)if(Object.defineProperties){var P=Object.getOwnPropertyDescriptor(N,O);P&&Object.defineProperty(M,O,P)}else M[O]=N[O];
M.prototype.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));Q(this)};
M.prototype.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.m&&(clearTimeout(this.m),this.m=void 0)};M.prototype.attributeChangedCallback=function(){Q(this)};
M.prototype.handleEvent=function(a){var b=this,c=a.type,d=a.detail;switch(c){case "click":this.o&&a.target===this.h?a.stopPropagation():a.target&&ha(a.target)?(a.stopPropagation(),ia(this,a.target)):R(this);break;case "camera-change":"user-interaction"===d.source&&(this.i&&this.i.parentNode&&this.i.parentNode.removeChild(this.i),R(this),ja(this));a.stopPropagation();J("camera-changed",this,d);break;case "preload":case "load":this.classList.add("ready");S(this);break;case "model-visibility":if(!d.visible)return;
this.B&&(C(!1),this.B=!1,this.j=!0,ka(this),J("scene-rendered",this,null),T(this).dismissPoster());break;case "poster-dismissed":requestAnimationFrame(function(){J("poster-dismissed",b,null)})}window.Enabler&&(c===studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH?(T(this).setAttribute("touch-action","none"),Enabler.reportEngagement(),D()):c===studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH&&(T(this).setAttribute("touch-action","pan-y"),D()))};
var T=function(a){a.h||(a.h=a.ownerDocument.createElement("model-viewer"),a.h.setAttribute("camera-controls",""),a.h.setAttribute("interaction-prompt","none"),a.h.setAttribute("loading","eager"),a.h.setAttribute("data-js-focus-visible",""),a.h.setAttribute("touch-action","pan-y"),a.h.addEventListener("click",a),a.h.addEventListener("model-visibility",a),a.h.addEventListener("preload",a),a.h.addEventListener("load",a),a.h.addEventListener("camera-change",a),a.h.addEventListener("poster-dismissed",
a),a.appendChild(a.h));return a.h},ka=function(a){if(a.hasAttribute("autoplay")){var b=T(a);b.pause();b.play();a=1E3*ea(a);0<=a&&I(function(){b.pause()},a)}},Q=function(a){a.m||(a.m=I(a.gwdLoad.bind(a),0))};
M.prototype.gwdLoad=function(){var a=this;this.m&&(clearTimeout(this.m),this.m=void 0);customElements.whenDefined("model-viewer").then(function(){var b=a.h?a.h.getAttribute("src"):null,c=U(a,"src",!0);if(c){c!==b&&(a.u=!1,a.classList.remove("ready"),a.B=!0,a.j=!1,C(!0));b=k(K);for(c=b.next();!c.done;c=b.next())c=c.value,"src"!==c&&U(a,c);a.h&&a.h.jumpCameraToGoal();a.syncHotspotsToViewer();a.i&&a.i.parentNode&&a.i.parentNode.removeChild(a.i);if(c=a.getAttribute("gesture-cue-icon")){a.i=a.ownerDocument.createElement("div");
a.i.classList.add("gesture-cue-container");b=a.ownerDocument.createElement("div");b.classList.add("gesture-cue-icon");b.style.backgroundImage='url("'+c+'")';c=v(a,"gesture-cue-duration");b.style.animationIterationCount=0>c?"infinite, 1":(c/2).toFixed(1)+", 1";a.i.appendChild(b);if(b=a.getAttribute("gesture-cue-text"))c=a.ownerDocument.createElement("p"),c.classList.add("gesture-cue-text"),c.textContent=b,a.i.appendChild(c);a.appendChild(a.i)}}else S(a)})};M.prototype.gwdIsLoaded=function(){return this.u};
var U=function(a,b,c){c=void 0===c?!1:c;var d=a.getAttribute(b);null==d||c&&!d?a.h&&a.h.removeAttribute(b):T(a).setAttribute(b,d);return a.h?a.h.getAttribute(b):null},S=function(a){a.u||(a.u=!0,J("ready",a))},Y=function(a){a.o&&(300<Date.now()-a.H?V(a,!1):requestAnimationFrame(function(){Y(a)}))},ja=function(a){a.H=Date.now();window.Enabler&&Enabler.reportEngagement();a.o||V(a,!0);requestAnimationFrame(function(){Y(a)})},V=function(a,b){b?(a.o=!0,document.addEventListener("mouseup",a.A),document.addEventListener("touchend",
a.A),H.Rotate&&H.Rotate(),E(!0),J("interaction-start",a)):(a.o=!1,E(!1),J("interaction-end",a))};M.prototype.G=function(){this.o&&(V(this,!1),document.removeEventListener("mouseup",this.A),document.removeEventListener("touchend",this.A))};
var ia=function(a,b){R(a);var c=T(a).getElementsByClassName("hotspot");for(var d=-1,e=0;e<c.length;e++)if(c[e]===b){d=e;var g=a;if(b.ownerDocument&&b.ownerDocument.body){var m=b.getElementsByClassName("hotspot-annotation");if(0!==m.length){m=m[0];m.style.transform="";g=g.getBoundingClientRect();var l=m.getBoundingClientRect(),w=l.right;l=l.bottom;var W=0,X=0;w>g.right&&(W=Math.round(g.right-w)-5);l>g.bottom&&(X=Math.round(g.bottom-l)-5);m.style.transform="translate3d("+W+"px, "+X+"px, 0px)"}}b.classList.add("selected");
a.v=b}c=d;if(-1!==c){d=b.getBoundingClientRect();e=b.querySelector("h3");b=b.querySelector("p");b={name:"Hotspot"+c,index:c,screenX:Math.round(d.left+d.width/2),screenY:Math.round(d.top+d.height/2),title:e?e.textContent:"",description:b?b.textContent:""};if(window.Enabler&&(Enabler.reportEngagement(),c="Hotspot"+(c+1)+"Click",H[c]))H[c]();J("hotspot-clicked",a,b)}};f=M.prototype;
f.setYaw=function(a){if(this.j){var b=T(this).getCameraOrbit(),c=T(this);c.cameraOrbit=a+"deg "+b.phi+"rad "+b.radius+"m";c.jumpCameraToGoal()}};f.setTargetYaw=function(a){if(this.j){var b=T(this).getCameraOrbit();T(this).cameraOrbit=a+"deg "+b.phi+"rad "+b.radius+"m"}};f.setTargetPitch=function(a){if(this.j){var b=T(this).getCameraOrbit();T(this).cameraOrbit=b.theta+"rad "+a+"deg "+b.radius+"m"}};
f.incrementTargetPitch=function(a){if(this.j){var b=T(this).getCameraOrbit();a=b.phi*L+a;T(this).cameraOrbit=b.theta+"rad "+a+"deg "+b.radius+"m"}};f.setTargetZoom=function(a){if(this.j){var b=T(this).getCameraOrbit();T(this).cameraOrbit=b.theta+"rad "+b.phi+"rad "+a+"m"}};f.incrementTargetZoom=function(a){if(this.j){var b=T(this).getCameraOrbit();a=b.radius+a;T(this).cameraOrbit=b.theta+"rad "+b.phi+"rad "+a+"m"}};f.setTargetPivot=function(a,b,c){this.j&&(T(this).cameraTarget=a+"m "+b+"m "+c+"m")};
f.setTargetLocalPan=function(a,b){if(this.j){var c=T(this),d=c.getCameraTarget().z;c.cameraTarget=a+"m "+b+"m "+d+"m"}};f.setMaterialColor=function(a,b,c,d){b=[b,c,d,1];c=T(this);c=k(c.model.materials);for(d=c.next();!d.done;d=c.next())if(d=d.value,d.name===a){d.pbrMetallicRoughness.setBaseColorFactor(b);break}};f.setMaterialClearCoat=function(){};f.playAnimation=function(a){var b=T(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.play()};
f.pauseAnimation=function(a){var b=T(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.pause()};f.setAnimationTime=function(a,b){var c=T(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.currentTime=b};f.incrementAnimationTime=function(a,b){var c=T(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.currentTime+=b};f.addHotspot=function(a,b,c,d){var e=T(this);a=Z({F:e,hotspotName:a,position:b+"m "+c+"m "+d+"m",normal:"",title:"",description:"",C:!0});e.appendChild(a)};
f.setHotspotInfoCard=function(a,b,c){var d=T(this);if(a=d.querySelector('div[slot="hotspot-'+a+'"]')){var e=a.getElementsByClassName("hotspot-annotation"),g=d.ownerDocument;0===e.length?(d=g.createElement("div"),d.classList.add("hotspot-annotation"),a.appendChild(d)):d=e[0];for(;d.firstChild;)d.removeChild(d.firstChild);a=g.createElement("h3");a.textContent=b;d.appendChild(a);b=g.createElement("p");b.textContent=c;d.appendChild(b)}};f.lookAtHotspot=function(){};f.lookAtHotspotIndex=function(){};
var R=function(a){a.v&&(a.v.classList.remove("selected"),a.v=null)},Z=function(a){var b=a.position,c=a.normal,d=a.title,e=a.description,g=a.C,m=a.F.ownerDocument,l=m.createElement("div");l.setAttribute("slot","hotspot-"+a.hotspotName);l.classList.add("hotspot");g&&l.setAttribute("info-card-hidden","");l.setAttribute("data-position",b);c&&l.setAttribute("data-normal",c);if(d||e)a=m.createElement("div"),a.classList.add("hotspot-annotation"),b=m.createElement("h3"),b.textContent=d,a.appendChild(b),d=
m.createElement("p"),d.textContent=e,a.appendChild(d),l.appendChild(a);return l};
M.prototype.syncHotspotsToViewer=function(){var a=T(this);if(a){for(var b=k(a.querySelectorAll(".hotspot")),c=b.next();!c.done;c=b.next())c=c.value,c.parentNode&&c.parentNode.removeChild(c);if(b=this.querySelector("gwd-3d-hotspot-container")){this.s&&(c=this.s,(c=c.ownerNode||c.owningElement||c)&&c.parentNode&&c.parentNode.removeChild(c),this.s=null,T(this).classList.remove(this.l));var d=b.getAttribute("up-image"),e=b.getAttribute("over-image"),g=b.getAttribute("down-image");c="";d&&(c+="model-viewer."+
this.l+' .hotspot { background: url("'+d+'") center / contain no-repeat; }');e&&(c+="model-viewer."+this.l+' .hotspot:hover { background: url("'+e+'") center / contain no-repeat; }');g&&(c+="model-viewer."+this.l+" .hotspot:active, model-viewer."+(this.l+' .hotspot.selected { background: url("')+g+'") center / contain no-repeat; }');d=b.getAttribute("width");e=b.getAttribute("height");if(d||e)c+="model-viewer."+this.l+" .hotspot {",d&&(c+="width: "+parseFloat(d)+"px; "),e&&(c+="height: "+parseFloat(e)+
"px; "),c+="}";d=b.getAttribute("background-color");e=b.getAttribute("font-color");g=b.getAttribute("border-color");if(d||e||g)c+="model-viewer."+this.l+" .hotspot-annotation {",d&&(c+="background-color: "+d+"; "),e&&(c+="color: "+e+"; "),g&&(c+="border-color: "+g+"; "),c+="}";c&&(T(this).classList.add(this.l),e=document,d=e.getElementsByTagName("head")[0],d||(g=e.getElementsByTagName("body")[0],d=e.createElement("head"),g.parentNode.insertBefore(d,g)),e=e.createElement("style"),e.textContent=c,d.appendChild(e),
this.s=e);c=0;b=k(b.children);for(d=b.next();!d.done;d=b.next())if(d=d.value,e=d.getAttribute("data-position")){g=d.getAttribute("data-normal")||"";var m=d.getAttribute("hotspot-name")||String(c),l=d.getAttribute("hotspot-title")||"",w=d.getAttribute("hotspot-description")||"";d=Z({F:a,hotspotName:m,position:e,normal:g,title:l,description:w,C:d.hasAttribute("info-card-hidden")});a.appendChild(d);c++}}}};var ha=function(a){return a.classList&&a.classList.contains("hotspot")?!0:!1};
M.prototype.getSceneGraphModel=function(){return T(this).model};M.prototype.getCameraDetails=function(){var a=T(this).getCameraOrbit(),b=a.theta,c=a.phi;a=a.radius;var d=T(this).getCameraTarget();return{yaw:b*L,pitch:c*L,zoom:a,x:d.x,y:d.y,z:d.z}};ba.Object.defineProperties(M,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return fa}}});customElements.define("gwd-3d-model-viewer",M);}).call(this);
