(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},n=ba(this),p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var ca={a:!0},r={};try{r.__proto__=ca;q=r.a;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var t=p,v=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.pa=b.prototype},x=this||self,y=function(a,b){function c(){}c.prototype=b.prototype;a.pa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qa=function(d,e,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,
f)}};var z=function(a,b,c,d){a="translate3d("+a+"px, "+b+"px, "+c+"px)";d&&(a="rotate3d(0, 1, 0, "+d+"deg) "+a);return a},A=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a};var B=["-ms-","-moz-","-webkit-",""],C=function(a,b,c,d){d=void 0===d?!1:d;for(var e,h,f=0;f<B.length;f++)e=B[f]+b,h=(d?B[f]:"")+c,a.style.setProperty(e,h)};var D=function(a,b){C(a,"transition","transform "+b+"ms",!0)};var E=function(a,b){return window.setTimeout(a,b)};var F=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},da=function(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;E(function(){var d=F("autoplayended",a,b);c&&c(d)},0)},ea=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},fa=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=E(function(){c=null;b&&(a(),b=!1)},250))}};var G=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},H=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ha=function(a){if(H(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&H(a))return a;return null},I=function(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,
a)):c.removeAttribute(d)},ia=function(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};function J(a){if(Error.captureStackTrace)Error.captureStackTrace(this,J);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}y(J,Error);J.prototype.name="CustomError";var K=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");J.call(this,c+a[d])};y(K,J);K.prototype.name="AssertionError";var ja=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new K(""+d,e||[]);}return a},ka=function(a,b){throw new K("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var M=function(a,b){this.K=b===L?a:""};M.prototype.da=!0;M.prototype.ca=function(){return this.K.toString()};M.prototype.toString=function(){return this.K.toString()};var la=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,L={};var N=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var h=a[c];h=h.trim();h=window.Enabler?window.Enabler.getUrl(h):h;var f=document.createElement("gwd-image");f.setAttribute("source",h);e.call(d,f)}}return b},O=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}},P=function(a,b){return"left"==a||"backwards"==a?-b:b},Q=function(a,
b){return(a%b+b)%b};var ma=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},R=function(a,b){this.m=a;this.s=null;this.na=b;this.H=!1};
R.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.m.frameCount&&null==this.s){if(c){var e=Math.floor(a/c);a=c}else e=this.m.frameCount,a/=e;var h=[],f=ma(this.m);c=f;for(var g=0;g<e;g++){if(0<g||!this.na)c=Q(c+P(b,1),this.m.frameCount);h.push(c)}b=function(){if(h.length){var l=h.shift();d.H=!0;d.m.goToFrame(l+1);d.H=!1;F("frameautoplayed",d.m,{id:l+1})}else d.stop(!0),d.m.goToFrame(f+1)};this.s=window.setInterval(b,a);setTimeout(b)}};
R.prototype.stop=function(a){a=void 0===a?!1:a;!this.H&&this.s&&(window.clearInterval(this.s),da(this.m,{completed:a}),this.s=null)};var na=["pause-front-media","resume-next-media"],S=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.g=null;a.h=0;a.B=1;a.v=new R(a,!0);a.U=!1;a.W=!1;return a};v(S,HTMLElement);k=S.prototype;k.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.U="true"==c;break;case "resume-next-media":this.W="true"==c}};k.gwdIsLoaded=function(){return!0};k.gwdLoad=function(){};k.goToFrame=function(a,b){this.stopRotation();0!=this.h&&(a>this.h?a=this.h:1>a&&(a=1),this.O(a,b))};
k.O=function(a){this.g=a-1};var T=function(a,b,c,d){if(null!=a.g){var e=a.B;e=Q(a.g+P(b,void 0===e?1:e),a.B*Math.ceil(a.h/a.B));!d&&("forwards"==b&&e<a.g||"backwards"==b&&e>a.g)||a.goToFrame(e+1,c)}};k=S.prototype;k.goBackwards=function(a,b){T(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};k.goForwards=function(a,b){T(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};k.rotateOnce=function(a,b){this.v.play(void 0===a?0:a,b)};k.stopRotation=function(){this.v.stop()};
k.getFrame=function(a){if(0!=this.h)return this.frames[a-1]};var U=function(a,b){if(null!=a.g&&a.g!=b){if(a.U)for(var c=Array.prototype.slice.call(a.frames[a.g].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),d=0;d<c.length;d++){var e=c[d];e.pause&&e.pause()}if(a.W)for(a=Array.prototype.slice.call(a.frames[b].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),b=0;b<a.length;b++)c=a[b],c.play&&c.play()}};
S.prototype.aa=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?F(d,this,{id:this.currentIndex}):F(d,this)}};n.Object.defineProperties(S.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.h?this.g+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.B}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.h}}});
n.Object.defineProperties(S,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return na}}});var oa="autoplay exit-urls transition-duration frame-width frame-height neighbor-rotation-y neighbor-translation-x neighbor-translation-y neighbor-translation-z start-frame show-reflection has-navigation navigation-highlight navigation-thumbnails images scaling pause-front-media resume-next-media".split(" "),V=function(){var a=S.call(this)||this;a.I=!1;a.l=null;a.P=-1;a.L=0;a.o=null;a.$=a.la.bind(a);a.Z=a.ma.bind(a);a.Y=a.ka.bind(a);a.X=a.ja.bind(a);a.G=F.bind(null,"firstinteraction",a);a.T=a.ha.bind(a);
a.V=fa(a.ia.bind(a));a.M=!1;a.J=[];a.u=a.aa.bind(a,a.J);a.F=[];a.N=0;a.C=!1;a.i=null;a.A=0;a.v=new R(a,!1);a.j=null;a.R=!1;a.D=!1;return a};v(V,S);k=V.prototype;
k.connectedCallback=function(){if(!this.D){if(this.C=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.o=a;this.D=!0}a=this.o;this.A=this.A||this.clientWidth/2;a.addEventListener("trackstart",this.$,!1);a.addEventListener("track",this.Z,!1);a.addEventListener("trackend",this.Y,!1);a.addEventListener("tap",this.X,!1);this.addEventListener("transitionend",this.u,!1);this.addEventListener("webkitTransitionEnd",
this.u,!1);this.gwdIsLoaded()||((a=ha(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.R&&W(this);window.addEventListener("resize",this.V,!1)};
k.disconnectedCallback=function(){window.removeEventListener("resize",this.V,!1);var a=this.o;a.removeEventListener("trackstart",this.$,!1);a.removeEventListener("track",this.Z,!1);a.removeEventListener("trackend",this.Y,!1);a.removeEventListener("tap",this.X,!1);this.removeEventListener("transitionend",this.u);this.removeEventListener("webkitTransitionEnd",this.u)};
k.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":this.C=!0;this.h=0;this.g=null;this.frames=N(c||"");W(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":this.D&&X(this);break;case "scaling":O(this.frames,c);break;case "pause-front-media":case "resume-next-media":S.prototype.attributeChangedCallback.call(this,a,b,c,d);break;default:pa(this)}};
k.O=function(a,b){b="none"!=b;var c=this.i.transitionDuration;U(this,a-1);Y(this,b?c:0);Z(this,a-1)};k.rotateOnce=function(a,b){this.v.play((void 0===a?0:a)||this.i.transitionDuration*this.h,b)};k.gwdIsLoaded=function(){return this.I};k.gwdLoad=function(){if(!this.I&&!this.l){if(this.C)var a=N(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;W(this)}};
var W=function(a){if(a.D){for(;a.firstChild;)a.removeChild(a.firstChild);a.j=null;a.l&&a.l.removeEventListener("pageload",a.T,!1);for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];C(e,"user-select","none");e.classList.add("frame");c.appendChild(e)}ea(c,c.gwdLoad.bind(c));a.l=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.T,!1);O(a.frames,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.o)}else a.R=
!0};V.prototype.ha=function(a){this.l===a.target&&(this.I=!0,this.h=this.frames.length,this.F=[],this.N=this.h,qa(this),this.h&&this.i.autoplay&&E(this.rotateOnce.bind(this),0),X(this),F("allframesloaded",this),F("ready",this))};var qa=function(a){ra(a);if(a.h){var b=a.i.oa-1;if(0>b||b>=a.h)b=0;Y(a,0);Z(a,b)}};V.prototype.ia=function(){this.A=this.clientWidth/2;qa(this)};
var ra=function(a){pa(a);for(var b=0,c,d=0;d<a.frames.length;d++)c=a.frames[d],c.style.left=b+"px",c.style.width=a.i.frameWidth+"px",c.style.height=a.i.frameHeight+"px",b+=a.i.frameWidth},pa=function(a){var b=a.frames;var c=A(a,"frame-width",Math.floor(.8*a.clientWidth));var d=a.hasAttribute("show-reflection"),e=A(a,"frame-height",d?Math.floor(4*a.clientHeight/7):Math.floor(6*a.clientHeight/7)),h=A(a,"neighbor-translation-x",Math.floor(c/8));if(a.hasAttribute("neighbor-translation-x")){a:{var f=c,
g=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var l=a.getAttribute("clamp-frame-size-to-image");"true"==l?g=!0:"false"==l&&(g=!1)}if(g)if(l=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",(g="contain"==l)||"none"==l)if(0==f||0==e)b=f;else{l=-1;c=b.length;for(var w=0;w<c;w++){var m=b[w];if("img"!=m.tagName.toLowerCase()&&"gwd-image"!=m.tagName.toLowerCase()){b=f;break a}var u=m.assetWidth?m.assetWidth:m.naturalWidth;m=m.assetHeight?m.assetHeight:m.naturalHeight;0<u&&0<m&&(l=Math.max(l,
g?u/m<f/e?u/m*e:f:u))}b=-1!=l?Math.min(f,l):f}else b=f;else b=f}c=b}b=A(a,"neighbor-translation-y",-Math.floor(e/10));f=A(a,"neighbor-translation-z",-e);g=A(a,"neighbor-rotation-y",38);l=A(a,"start-frame",2);u=e;a.j&&(u-=36);e=ia(a);w=a.hasAttribute("autoplay");m=parseInt(a.getAttribute("transition-duration"),10);isNaN(m)&&(m=600);a.i={autoplay:w,ba:e,frameWidth:c,frameHeight:u,ea:g,fa:h,S:b,ga:f,transitionDuration:m,ra:d,oa:l}};
V.prototype.la=function(){null!=this.g&&(this.stopRotation(),this.L=this.g,Y(this,0))};V.prototype.ma=function(a){if(this.h){this.G&&(this.G(),this.G=null);a=-a.dx/this.i.frameWidth;var b=Math.round(a);sa(this,this.L+b,a-b)}};V.prototype.ka=function(){if(null!=this.g){Y(this,this.i.transitionDuration);var a=this.g;Z(this,a);this.L!=a&&(0==a?F("reachleftend",this):a==this.h-1&&F("reachrightend",this))}};
V.prototype.ja=function(a){if(this.h){var b=null;var c=this.o;var d=this.l,e=a.clientX,h=a.clientY,f=c.style["pointer-events"];c.style["pointer-events"]="none";e=d.ownerDocument.elementFromPoint(e,h);c.style["pointer-events"]=f;if(c=e&&G(d,e)?e:null){d=a.clientX;a=a.clientY;f=!1;"gwd-taparea"===c.tagName.toLowerCase()&&(f=c.ownerDocument.createEvent("Event"),f.initEvent("action",!0,!0),f.clientX=d,f.clientY=a,f=!c.dispatchEvent(f));if(f)return;for(a=0;a<this.h;a++)if(G(this.frames[a],c)){b=a;break}null!=
b&&(a=this.i.ba[b])&&!F("frameexit",this,{url:a}).detail.handled&&(a instanceof M||a instanceof M||(a="object"==typeof a&&a.da?a.ca():String(a),ja(la.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new M(a,L)),c=a,a=x.open,c instanceof M&&c.constructor===M?c=c.K:(d=typeof c,ka("expected object of type SafeUrl, got '"+c+"' of type "+("object"!=d?d:c?Array.isArray(c)?"array":d:"null")),c="type_error:SafeUrl"),a.call(x,c,""))}null==b&&(b=null!=this.g?this.g:0);F("frametap",
this,{element:this.frames[b],id:b+1})}};
var Y=function(a,b){a.M=0<b;a.l&&D(a.l,b);for(var c=0;c<a.h;c++)D(a.frames[c],b)},Z=function(a,b){a.frames[b]&&(a.g=b,sa(a,b,0,a.h),a.J.push("frameshown"),a.F[b]||(a.F[b]=!0,--a.N||a.J.push("allframesviewed")));a.M||a.u()},sa=function(a,b,c,d){d=void 0===d?1:d;for(var e=a.i,h,f,g=-d;g<=d;g++)if((h=a.frames[g+b])&&0<=c*g){0>g?f=1-Math.abs(c):0<g?f=Math.abs(c)-1:(U(a,b),a.g=b,f=c);var l=Math.abs(f);h.style.setProperty("transform",z(e.fa*f,e.S*l,e.ga*l,e.ea*f))}a.P!=a.g&&null!=a.g&&(a.P=a.g,F("frameactivated",
a,{id:a.currentIndex}));a.l.style.setProperty("transform",z(a.A-(b+c+.5)*e.frameWidth,-e.S,0,void 0))},X=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.j;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.j=document.createElement("gwd-gallerynavigation"),a.j.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.j)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.j),a.j=null);a.j&&(I(a,"navigation-highlight",a.j,"highlight"),I(a,"navigation-thumbnails",a.j,
"use-thumbnails"));ra(a)};n.Object.defineProperties(V,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return oa}}});customElements.define("gwd-carouselgallery",V);}).call(this);
