(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},l=k(this),n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={a:!0},t={};try{t.__proto__=q;p=t.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=n;var v="currentIndex frameCount frameSnapInterval getFrame goToFrame goForwards goBackwards rotateOnce".split(" ");var w={A:"for",B:"highlight",C:"use-thumbnails"},x=[],y=0,z;for(z in w)x[y++]=w[z];var A=function(){var a=HTMLElement.call(this)||this;a.g=null;a.o=a.v.bind(a);a.m=a.u.bind(a);a.l=!1;a.h=null;a.i=[];a.j=!1;return a},B=HTMLElement;A.prototype=e(B.prototype);A.prototype.constructor=A;if(u)u(A,B);else for(var C in B)if("prototype"!=C)if(Object.defineProperties){var D=Object.getOwnPropertyDescriptor(B,C);D&&Object.defineProperty(A,C,D)}else A[C]=B[C];
A.prototype.connectedCallback=function(){if(!this.j){for(;this.firstChild;)this.removeChild(this.firstChild);this.h=this.ownerDocument.createElement("div");this.h.classList.add("button-container");this.appendChild(this.h);this.j=!0}this.h.addEventListener("click",this.s.bind(this),!0);E(this)};A.prototype.disconnectedCallback=function(){this.h.removeEventListener("click",this.s.bind(this));F(this)};A.prototype.attributeChangedCallback=function(a){if(this.j)switch(a){case "for":E(this);break;default:G(this)}};
var E=function(a){F(a);var b=a.getAttribute("for"),c=null,f=!1,g=!1;if(b){c=document.getElementById(b);for(var h=!1,d=a.parentElement;!c&&d&&!h;d=d.parentElement)if((h="body"==d.tagName.toLowerCase())||d.hasAttribute("data-gwd-group"))c=d.querySelector('[data-gwd-grp-id="'+b+'"]');if(c){a:if(c){for(b=0;b<v.length;b++)if(!(v[b]in c)){f=!1;break a}f=!0}else f=!1;g="gwd-transitiongallery"===c.tagName.toLowerCase()}}if(f||g)a.g=c,c.addEventListener("frameactivated",a.m),c.gwdIsLoaded()?G(a):c.addEventListener("ready",
a.o)},F=function(a){a.g&&(a.g.removeEventListener("ready",a.o),a.g.removeEventListener("frameactivated",a.m))};A.prototype.v=function(a){a.target==this.g&&G(this)};A.prototype.u=function(a){a.target==this.g&&H(this,a.detail.id)};A.prototype.s=function(a){for(a=a.target;a&&a!=this;a=a.parentElement)if(a.gwdTargetFrameNum){this.g.goToFrame(a.gwdTargetFrameNum);break}};
var G=function(a){var b=a.getAttribute("highlight");a.style.color=b||"";a.l=a.hasAttribute("use-thumbnails");for(a.i=[];a.h.firstChild;)a.h.removeChild(a.h.firstChild);if(a.g){b=a.g.frameSnapInterval||1;for(var c=a.l?b:1,f=0;f<a.g.frameCount;f+=b){var g=document.createElement("span");g.classList.add("button");for(var h=0;h<c;h++){var d=a.g.getFrame(f+h+1);if(!d)break;var r=void 0,m=document.createElement("span");a.l?(m.classList.add("frame-thumbnail"),(d="gwd-image"==d.tagName.toLowerCase()||"img"==
d.tagName.toLowerCase()?d:d.querySelector("gwd-image"))&&(r=d.getAttribute("source")||d.getAttribute("src")),m.style.backgroundImage=r?"url("+JSON.stringify(r)+")":"url(data:image/gif;base64,R0lGODlhAQABAPAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==)"):m.classList.add("frame-dot");g.appendChild(m)}g.gwdTargetFrameNum=f+1;a.i.push(g);a.h.appendChild(g)}H(a)}},H=function(a,b){b=void 0!=b?b-1:a.g.currentIndex-1;a.g.frameSnapInterval&&(b=Math.floor(b/a.g.frameSnapInterval));for(var c=0;c<a.i.length;c++)a.i[c].classList.remove("active");
(a=a.i[b])&&a.classList.add("active")};l.Object.defineProperties(A,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return x}}});customElements.define("gwd-gallerynavigation",A);}).call(this);
